# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to development.
#
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'projects/caig-admin/**'
      - 'projects/file-upload/**'
      - 'projects/vs-table/**'
      - 'projects/export-csv/**'
      - 'projects/sidenav-stack/**'
      - 'projects/tree-viewer/**'

env:
  AZURE_WEBAPP_NAME: caigsurveytest
  AZURE_WEBAPP_PACKAGE_PATH: './dist/survey'
  NODE_VERSION: '14.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build
        run: |
          # Build the project, then
          # deploy to Azure Web App.
          npm install
          npm run build:survey
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.CAIGSURVEYTEST_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
